### ISSUE TITLE
Startseite:

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/pmi_redesign#10]
Hier meine Änderungen bezüglich der Startseite:

Hierzu die Invision Vorlage:
https://horvat935689.invisionapp.com/public/share/NYWU06Y38#/screens/474594353

---

1. Zeilenumbruch: Ist es möglich die 1. Überschrift: We are the Black Forest ... mit so nem Zeilenumbruch wie in Invision darzustellen?

---

2. Bühne sollte sich nicht bewegen. Einfach nur Text.

---

3. Link zu Produktseite und Innovations unter Text bei Doro sollte blau sein und Linie unterhalb der "Doro Section" fehlt:

<img width="1233" alt="s4" src="https://user-images.githubusercontent.com/47521462/69493905-3b00d080-0eb5-11ea-8750-7add885a0611.png">
 
---

4. Icons und Verlinkungen auf Seite fehlen.
<img width="1245" alt="s5" src="https://user-images.githubusercontent.com/47521462/69493934-aea2dd80-0eb5-11ea-9658-65c655b1fca8.png">

---

5. Design unterhalb Doro ist nicht so wie Design von Stjepan

---

6. News- section fehlt komplett

---

7. 2. Footer muss angepasst werden:
a) Zeilenumbruch bei "Lets get Coonected" ***
b) Namen der UN sollte auf gleicher Ebene ändern damit die Adresse auf derselben Ebene beginnen kann 

<img width="1255" alt="s6" src="https://user-images.githubusercontent.com/47521462/69494047-33dac200-0eb7-11ea-8218-915e95057f55.png">

c) Link "View full contact information" sollte noch in anthrazit Section sein ***

---

8.
"© 2018 pro med instruments GmbH" sollte "© 2019 pro med instruments GmbH "oder schon "© 2020 pro med instruments GmbH" heißen

**Comment by steffi501** [comment]
Sollte nun alles soweit passen - die News Section fehlt aktuell, weil wir uns am aktuellen Inhalt orientiert haben und das Budget ja quasi schon rum ist. Können wir aber gern noch einsetzen, gibts nur aktuell noch nicht...

**Comment by AlisaNikia** [comment]
done (außer news section, siehe dazu Issue #24
