### ISSUE TITLE
Seite: Who we are

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/pmi_redesign#15]
Folgendes sollte geändert werden:
http://stage.pmisurgical.com/about-us/who-we-are/

1. Bild in der Stage: ist etwas unscharf. Liegt das am Bild? Muss der Kunde Bildformat ändern?

---

2. Bei Stronger together fehlt die horizontale Linie
<img width="1241" alt="s5" src="https://user-images.githubusercontent.com/47521462/69494607-12310900-0ebe-11ea-9f26-366a2f78fe2d.png">

---

3. Textfeld sollte nicht bold und so groß sein
<img width="1237" alt="s6" src="https://user-images.githubusercontent.com/47521462/69494629-473d5b80-0ebe-11ea-81ff-8f5315e46a48.png">

---

4. Part "Our Mission" ist hier nicht vorgesehen

---

5. Slider stimmt nicht mit Invision überein. Image ist nicht sichtbar und Text sollte rechts neben Slider erscheinen
---

6. Icon Set fehlt

---

7. Bild am unteren Rand sollte noch hellgraue Section haben, wenn möglich ***

**Comment by AlisaNikia** [comment]
Ok, hab grad gesehen,dass Du dich da an die jetzigen Textgegebenheiten gehlaten hast. Da hast Du vollkommen Recht!!

Our Mission bleibt!!

**Comment by steffi501** [comment]
1. Ja genau, die Bilder müssten jetzt so 600 x 400 Pixel groß sein und sollten nicht mehr so querformatig sein. Ich hab das aus dem bestehenden Bild ausgeschnitten, deshalb ist es etwas unscharf. 

2. Bild tausch ich noch aus

5. Muss neu gepflegt werden, der Text war hier bisher im Bild mit drin...

**Comment by AlisaNikia** [comment]
done außer Linie (Nummer 2)
