### ISSUE TITLE
Seite: PMI family

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/pmi_redesign#17]
Muss dem Design angepasst werden

---
- Übersichtsseite sieht noch etwas durcheinander aus
http://stage.pmisurgical.com/about-us/pmi-family/

- Individuelle Seite muss dem Design angepasst werden
http://stage.pmisurgical.com/about-us/pmi-family/single-view/team/person/gutmann/

**Comment by steffi501** [comment]
Sollte nun passen.
- Bühne muss noch gepflegt werden
- Die Bilder der Teammitglieder für die Detailseite dürfen nicht mehr quadratisch sein, sehen deshalb grad noch etwas anders aus - steht auch auf der Liste ;)

**Comment by AlisaNikia** [comment]
done
