### ISSUE TITLE
Seite: latest News

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/pmi_redesign#18]
http://stage.pmisurgical.com/about-us/latest-news/

Hier wurde der erste Eintrag ("There is no perfect player, only a perfect team.")
zweimal. Erster Post ist: "Team Black Forest Medical Group Participating in Fundraising Running Event"

Kann ich auch machen.

**Comment by steffi501** [comment]
@AlisaNikia Musste hier noch ein bisschen in den News rumkonfigurieren. Nachdem die erste News ein anderes Layout hat, verwenden wir hierfür die Topnews. Das erste Element ist also die aktuellste Newsmeldung, die als "Topnews" markiert ist. Danach folgen wie gehabt die anderen Einträge. Die doppelte Newsmeldung wird jetzt ausgeblendet. Passt das so? :)

**Comment by AlisaNikia** [comment]
done!
