### ISSUE TITLE
Seite: Life at PMI

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/pmi_redesign#19]
**Änderungen**
- Hier die Bühne fixen, siehe #16 
- icons tauschen

http://stage.pmisurgical.com/work-with-us/life-at-pmi/

**Comment by steffi501** [comment]
@AlisaNikia  Icons müssen noch ausgetauscht werden, das kann ich machen sobald ich sie hab. Bei der Bühne muss ggf. noch Text gepflegt werden

**Comment by AlisaNikia** [comment]
Muss Stjepan die noch liefern?

**Comment by AlisaNikia** [comment]
done
