### ISSUE TITLE
Seite: Contact

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/pmi_redesign#21]
Stimmt nicht mit dem Design überein

Soll:
<img width="1262" alt="s1" src="https://user-images.githubusercontent.com/47521462/69495937-e406f580-0ecc-11ea-9c01-a109155e715a.png">

Ist:

<img width="1254" alt="s4" src="https://user-images.githubusercontent.com/47521462/69495951-0862d200-0ecd-11ea-9281-263f861c3b81.png">

COTACT ist nun ne eigene Seite. Wenn dies vom Aufwand her zu viel ist, bitte versuchen so nah wie möglich am Design zu sein

**Comment by steffi501** [comment]
@AlisaNikia Ich denke, das hier ist die Kontaktseite? http://stage.pmisurgical.com/full-contact-details/ (Funktionalität wie bisher) Muss nur noch die Weltkarte einsetzen und den Slider rauswerfen...

**Comment by AlisaNikia** [comment]
Ah ok, dann passt es.
Ja, sollte so aussehen: 
https://horvat935689.invisionapp.com/public/share/NYWU06Y38#/screens/474646417

Dann gibt es aber diese Menüleiste nicht, wenn wir auf "Contact" gehen, oder?

<img width="1269" alt="s1" src="https://user-images.githubusercontent.com/47521462/69497342-2ab01c00-0edc-11ea-9ac2-1d47cc8b958c.png">

**Comment by steffi501** [comment]
Wie besprochen, wir lassen die Funktionalität erstmal so. Wenn wir die Kontaktseite direkt verlinken sollen, muss es der Kunde sagen :)
