### ISSUE TITLE
Background Image (allgemein)

### ISSUE THREAD

**Issue by AlisaNikia** [gebruederheitz/pmi_redesign#22]
Es scheint, dass das verwendete Background Image  anders ist als im Design:

<img width="1255" alt="s2" src="https://user-images.githubusercontent.com/47521462/69495973-3fd17e80-0ecd-11ea-80f0-254d8f4c07b3.png">

Der hellgraue Hintergrund fehlt komplett

**Comment by steffi501** [comment]
Seitenlayout muss im TYPO3 ausgewählt werden, der Default ist "nur" schwarzer Hintergrund. Wir können aber auch das hier als Default verwenden - passt nur bei den meisten Seiten mit Bühne dann nicht...

**Comment by AlisaNikia** [comment]
ok, wenn man es austauschen kann, ist das ganz großartig!
